[package]
name = "beam"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.6"
sipper = "0.1"
tokio = "1.47.1"
image = { version = "0.25", default-features = false }
iced = { version = "0.13.1", features = ["tokio", "image", "debug", "canvas", "advanced"] }

iced_aw = { version = "0.12.2", features = ["context_menu"] }


reqwest.version = "0.12"
reqwest.features = ["json", "blocking"]

serde.version = "1.0"
serde.features = ["derive"]

blurhash = "0.2.3"

