[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.31.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish pre-releases to GitHub
prereleases = true
# Allow dirty generated files
allow-dirty = ["ci"]

# Configure the runner specifically for Linux
[dist.github-runners]
aarch64-unknown-linux-gnu = "ubuntu-22.04"
x86_64-unknown-linux-gnu = "ubuntu-22.04"

[dist.dependencies.apt]
libgtk-3-dev = '*'
libappindicator3-dev = '*'
librsvg2-dev = '*'
